### ISSUE TITLE
Feedback: Oppgave 5: Prosjekt Del B

### ISSUE THREAD

**Issue by webminz** [r1nov8/ing301gruppeA2#1]
Dere har gjort en veldig solid jobb med implementasjonen av prosjektet. Det er tydelig at dere har forstått oppgaven godt og har klart å anvende de nødvendige teknikkene for å løse oppgavene på en effektiv måte. Her er noen tilbakemeldinger på deres innsending:

## Det som ble gjort bra:
- Oppsettet av databasen ved å bruke `CREATE TABLE IF NOT EXISTS` i `setup_database()`-metoden sikrer at tabellene kun opprettes én gang uavhengig av hvor mange ganger metoden kalles. Dette er en god praksis.
- Bruk av `INNER JOIN` i SQL-spørringene for å hente ut relevante data fra relaterte tabeller viser god forståelse av databaserelasjoner.
- Dynamisk bygging av SQL-spørring basert på input-parametere i `calc_avg_temperatures_in_room` illustrerer grundig forståelse av Python og SQLite.
- Måten dere håndterer tilkoblingen til databasen på, ved å både initialisere denne i `__init__` ogtilby en `reconnect`-metode, er god praksis for å redusere risikoen for tilkoblingsproblemer.

## Mulige forbedringsområder

Det virkelig velid lite som kan påpekes her, kanskje bare litt vedr. exception-håndtering og kommentarer:

- Det er viktig å håndtere potensielle exceptions som kan oppstå under databaseoperasjoner for å unngå at applikasjonen krasjer. Dette kan gjøres ved å innføre try/except-blokker rundt databasekallene.
- Kommentarene og dokumentasjonen er på enkelte områder noe mangelfulle. Å forsyne koden med tydelige og konsise kommentarer øker lesbarheten og vedlikeholdbarheten av koden.

Overordnet sett er dette en veldig sterk prestasjon!

Dere kan bare _lukke_ dette "issue" som _løst_ når dere har lest gjenomm den :wink:

**Comment by r1nov8** [comment]
Takker for tilbakemelding
